style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    max: 4

complexity:
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignorePrivate: true

naming:
  FunctionNaming:
    ignoreAnnotated: ["Composable"]

comments:
  active: false
